spring:
  application:
    name: petshop-bff-desktop
  web:
    resources:
      add-mappings: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      enabled-by-default: true

server:
  port: 9998
  servlet:
    context-path: /petshop-bff-desktop
    encoding:
      charset: UTF-8
      enabled: true
  max-http-request-header-size: 48000

---
spring:
  config:
    activate:
      on-profile: dev

redis:
  host: localhost
  port: 6379
  database: 1

webclient:
  default:
    api-gateway-address: http://localhost:9999/petshop-system
    api-gateway-timeout: 2500

---
spring:
  config:
    activate:
      on-profile: docker

redis:
  host: redis
  port: 6379
  database: 1

webclient:
  default:
    api-gateway-address: http://petshop-api-gateway:9999/petshop-system
    api-gateway-timeout: 2500
